CREATE TABLE `comments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `MUSIC_NAME` varchar(100) NOT NULL,
  `ARTIST_NAME` varchar(100) NOT NULL,
  `COMMENTS` varchar(200) NOT NULL,
  `DETAILS` varchar(500) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=234 DEFAULT CHARSET=utf8;
CREATE TABLE `comments2` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `MUSIC_NAME` varchar(100) NOT NULL,
  `ARTIST_NAME` varchar(100) NOT NULL,
  `COMMENTS` varchar(200) NOT NULL,
  `DETAILS` varchar(500) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=234 DEFAULT CHARSET=utf8;